Repository dormitoryFamilies/iOS, pull requests merged in 2024-07, with the labels that each got.

#53 [DESIGN] 긱사생활 설정 레이아웃 - 본가주기, 식습관, 휴대폰/향수, 공부습관 뷰
  dormitoryFamiles/Podfile.lock
  dormitoryFamiles/dormitoryFamiles.xcodeproj/project.pbxproj
  dormitoryFamiles/dormitoryFamiles.xcworkspace/xcshareddata/swiftpm/Package.resolved
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/Matching Option Setting/eatingFood_logo.imageset/eatingFood_logo.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/serviceCamera 2.imageset/_레이어_1 16.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tabbarItemBulletinBoard 2.imageset/게시판 아이콘 15.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tabbarItemBulletinBoard 2.imageset/게시판 아이콘 16.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tabbarItemBulletinBoard 2.imageset/게시판 아이콘 17.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tabbarItemBulletinBoardGray 2.imageset/_레이어_1 10.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tabbarItemBulletinBoardGray 2.imageset/_레이어_1 12.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tabbarItemChatting 2.imageset/채팅아이콘 14.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tabbarItemChatting 2.imageset/채팅아이콘 15.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tabbarItemChatting 2.imageset/채팅아이콘 16.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tabbarItemChattingGray 2.imageset/_레이어_1 (2) 10.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tabbarItemChattingGray 2.imageset/_레이어_1 (2) 5.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tabbarItemHome 2.imageset/홈아이콘 13.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tabbarItemHome 2.imageset/홈아이콘 14.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tabbarItemHome 2.imageset/홈아이콘 9.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tabbarItemHomeGray 2.imageset/_레이어_1 (1) 7.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tabbarItemHomeGray 2.imageset/_레이어_1 (1) 8.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tabbarItemHomeGray 2.imageset/_레이어_1 (1) 9.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tabbarItemMateMatching 2.imageset/룸메매칭아이콘 11.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tabbarItemMateMatching 2.imageset/룸메매칭아이콘 12.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tabbarItemMateMatching 2.imageset/룸메매칭아이콘 14.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tabbarItemMateMatchingGray 2.imageset/_레이어_1 (3) 7.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tabbarItemMateMatchingGray 2.imageset/_레이어_1 (3) 9.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tabbarItemMyPage 2.imageset/마이페이지 아이콘 12.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tabbarItemMyPage 2.imageset/마이페이지 아이콘 13.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tabbarItemMyPage 2.imageset/마이페이지 아이콘 9.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tabbarItemMyPageGray 2.imageset/_레이어_1 (4) 7.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tabbarItemMyPageGray 2.imageset/_레이어_1 (4) 8.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tabbarItemMyPageGray 2.imageset/_레이어_1 (4) 9.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tulletinBoardProfile.imageset/_레이어_2 7.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tulletinBoardProfile.imageset/_레이어_2 8.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tulletinBoardProfile.imageset/_레이어_2 9.svg
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/View/SleepPatternCircleCollectionViewCell.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/EatingFoodViewController.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/HomeCycleViewController.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/MBTIViewController.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/NoiseAndPerfumeViewController.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/StudyStyleViewController.swift
Labels: iOS, FEAT, DESIGN

#59 [FIX] 깃 충돌 해결
  .DS_Store
  dormitoryFamiles/dormitoryFamiles/Base/Base.lproj/Main.storyboard
  dormitoryFamiles/dormitoryFamiles/BulletinBoard/BulletinBoardDetailViewViewController.swift
  dormitoryFamiles/dormitoryFamiles/Network/Codable.swift
Labels: iOS, FIX

#61 [DESIGN] 긱사생활 설정 레이아웃 - 우선순위 설정 뷰
  dormitoryFamiles/dormitoryFamiles.xcodeproj/project.pbxproj
  dormitoryFamiles/dormitoryFamiles/App/Info.plist
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/serviceCamera 2.imageset/_레이어_1 16.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tabbarItemBulletinBoard 2.imageset/게시판 아이콘 15.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tabbarItemBulletinBoard 2.imageset/게시판 아이콘 16.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tabbarItemBulletinBoard 2.imageset/게시판 아이콘 17.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tabbarItemBulletinBoardGray 2.imageset/_레이어_1 10.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tabbarItemBulletinBoardGray 2.imageset/_레이어_1 12.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tabbarItemChatting 2.imageset/채팅아이콘 14.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tabbarItemChatting 2.imageset/채팅아이콘 15.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tabbarItemChatting 2.imageset/채팅아이콘 16.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tabbarItemChattingGray 2.imageset/_레이어_1 (2) 10.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tabbarItemChattingGray 2.imageset/_레이어_1 (2) 5.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tabbarItemHome 2.imageset/홈아이콘 13.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tabbarItemHome 2.imageset/홈아이콘 14.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tabbarItemHome 2.imageset/홈아이콘 9.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tabbarItemHomeGray 2.imageset/_레이어_1 (1) 7.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tabbarItemHomeGray 2.imageset/_레이어_1 (1) 8.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tabbarItemHomeGray 2.imageset/_레이어_1 (1) 9.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tabbarItemMateMatching 2.imageset/룸메매칭아이콘 11.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tabbarItemMateMatching 2.imageset/룸메매칭아이콘 12.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tabbarItemMateMatching 2.imageset/룸메매칭아이콘 14.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tabbarItemMateMatchingGray 2.imageset/_레이어_1 (3) 7.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tabbarItemMateMatchingGray 2.imageset/_레이어_1 (3) 9.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tabbarItemMyPage 2.imageset/마이페이지 아이콘 12.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tabbarItemMyPage 2.imageset/마이페이지 아이콘 13.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tabbarItemMyPage 2.imageset/마이페이지 아이콘 9.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tabbarItemMyPageGray 2.imageset/_레이어_1 (4) 7.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tabbarItemMyPageGray 2.imageset/_레이어_1 (4) 8.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tabbarItemMyPageGray 2.imageset/_레이어_1 (4) 9.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tulletinBoardProfile.imageset/_레이어_2 7.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tulletinBoardProfile.imageset/_레이어_2 8.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/tulletinBoardProfile.imageset/_레이어_2 9.svg
  dormitoryFamiles/dormitoryFamiles/Base/ko.lproj/LaunchScreen.strings
  dormitoryFamiles/dormitoryFamiles/Base/ko.lproj/Main.strings
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/View/PriorityCell.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/ChoosePriorityViewController.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/CompleteMyCondition.swift
Labels: iOS

#62 [FEAT] 룸메 매칭 데이터 모델링 및 버그 픽스
  dormitoryFamiles/dormitoryFamiles.xcodeproj/project.pbxproj
  dormitoryFamiles/dormitoryFamiles/Extension/UserDefaults+.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/View/SleepPatternCircleCollectionViewCell.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/View/SleepPatternCollectionViewCell.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/SleepPatternViewController.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/SmokeAndAlcoholPatternViewController.swift
Labels: iOS, FEAT, FIX

#64 [FEAT] 댓글관련 디테일 작업
  dormitoryFamiles/ReplyCollectionViewCell.swift
  dormitoryFamiles/dormitoryFamiles.xcodeproj/project.pbxproj
  dormitoryFamiles/dormitoryFamiles.xcworkspace/xcshareddata/swiftpm/Package.resolved
  dormitoryFamiles/dormitoryFamiles/BulletinBoard/BrownVC.swift
  dormitoryFamiles/dormitoryFamiles/BulletinBoard/BulletinBoardDetailViewViewController.swift
  dormitoryFamiles/dormitoryFamiles/BulletinBoard/BulluetinBoardCollectionViewCell.xib
  dormitoryFamiles/dormitoryFamiles/BulletinBoard/ReplyHeaderCollectionReusableView.swift
  dormitoryFamiles/dormitoryFamiles/BulletinBoard/ReplyHeaderCollectionReusableView.xib
  dormitoryFamiles/dormitoryFamiles/BulletinBoard/SearchViewController.swift
  dormitoryFamiles/dormitoryFamiles/Network/Codable.swift
  dormitoryFamiles/dormitoryFamiles/ReplyCollectionViewCell.xib
Labels: iOS, FEAT

#65 [FEAT] 선택한 Cell 데이터 저장 로직 구현
  dormitoryFamiles/dormitoryFamiles/Extension/UserDefaults+.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/ConstitutionViewController.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/EatingFoodViewController.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/HomeCycleViewController.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/LifeStyleViewController.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/MBTIViewController.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/MiscViewController.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/NoiseAndPerfumeViewController.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/SleepPatternViewController.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/SmokeAndAlcoholPatternViewController.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/StudyStyleViewController.swift
Labels: iOS, FEAT

#66 [DESIGN] 채팅홈 UI
  dormitoryFamiles/dormitoryFamiles.xcodeproj/project.pbxproj
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/chatSearch.imageset/Contents.json
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/chatSearch.imageset/chatSearch.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/gray2.colorset/Contents.json
  dormitoryFamiles/dormitoryFamiles/Base/Base.lproj/Main.storyboard
  dormitoryFamiles/dormitoryFamiles/BulletinBoard/BulletinBoardDetailViewViewController.swift
  dormitoryFamiles/dormitoryFamiles/Components/CommomButton.swift
  dormitoryFamiles/dormitoryFamiles/Extension/TagButton.swift
  dormitoryFamiles/dormitoryFamiles/Manager/FontManager/FontManager.swift
  dormitoryFamiles/dormitoryFamiles/chat/ChatFollowingCollectionViewCell.swift
  dormitoryFamiles/dormitoryFamiles/chat/ChattingHomeTableViewCell.swift
  dormitoryFamiles/dormitoryFamiles/chat/ChattingHomeViewController.swift
Labels: iOS, DESIGN

#72 [FEAT] 채팅홈/검색화면 API 연동
  dormitoryFamiles/dormitoryFamiles.xcodeproj/project.pbxproj
  dormitoryFamiles/dormitoryFamiles/Components/LabelAndPrimaryMidButtonStackView.swift
  dormitoryFamiles/dormitoryFamiles/Extension/ExtenstionColor.swift
  dormitoryFamiles/dormitoryFamiles/Extension/Stroyboard+.swift
  dormitoryFamiles/dormitoryFamiles/Extension/UIButton+.swift
  dormitoryFamiles/dormitoryFamiles/Extension/UIColor+.swift
  dormitoryFamiles/dormitoryFamiles/Extension/UILabel+.swift
  dormitoryFamiles/dormitoryFamiles/Network/Codable.swift
  dormitoryFamiles/dormitoryFamiles/chat/ChattingHomeViewController.swift
  dormitoryFamiles/dormitoryFamiles/chat/SearchChat/AllDoomzViewController.swift
  dormitoryFamiles/dormitoryFamiles/chat/SearchChat/AllViewController.swift
  dormitoryFamiles/dormitoryFamiles/chat/SearchChat/ChattingRoomViewController.swift
  dormitoryFamiles/dormitoryFamiles/chat/SearchChat/FollowingViewController.swift
  dormitoryFamiles/dormitoryFamiles/chat/SearchChattingViewController.swift
Labels: iOS, FEAT

#78 [FEAT] 필수 옵션 선택 시 버튼 활성화 로직, 버튼 재선택 시 선택 해제 로직 구현
  dormitoryFamiles/dormitoryFamiles.xcodeproj/project.pbxproj
  dormitoryFamiles/dormitoryFamiles.xcworkspace/xcshareddata/swiftpm/Package.resolved
  dormitoryFamiles/dormitoryFamiles/Components/CommomButton.swift
  dormitoryFamiles/dormitoryFamiles/Components/ConfigUI.swift
  dormitoryFamiles/dormitoryFamiles/Extension/UICollectionView+.swift
  dormitoryFamiles/dormitoryFamiles/Extension/UIScreen+.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/SleepPatternViewController.swift
Labels: iOS, FEAT
