Repository dormitoryFamilies/iOS, pull requests merged in 2024-05, with the labels that each got.

#27 [FEAT] 게시판글쓰기-사진관련 업데이트
  .DS_Store
  .gitignore
  dormitoryFamiles/.gitignore
  dormitoryFamiles/dormitoryFamiles/BulletinBoard/BrownVC.swift
  dormitoryFamiles/dormitoryFamiles/BulletinBoard/PhotoScrollView.swift
  dormitoryFamiles/dormitoryFamiles/BulletinBoard/RegisterPostViewController.swift
  dormitoryFamiles/dormitoryFamiles/BulletinBoard/SearchViewController.swift
  dormitoryFamiles/dormitoryFamiles/Network/Codable.swift
  dormitoryFamiles/dormitoryFamiles/Network/Token.swift
  dormitoryFamiles/dormitoryFamiles/Network/Url.swift
Labels: FEAT

#29 [#28] FEAT: 게시글조회(게시글정렬 업데이트, 모집완료태그 세팅, 프로필/썸네일 사진적용)
  dormitoryFamiles/Podfile
  dormitoryFamiles/Podfile.lock
  dormitoryFamiles/dormitoryFamiles.xcodeproj/xcuserdata/hwajin.xcuserdatad/xcschemes/xcschememanagement.plist
  dormitoryFamiles/dormitoryFamiles/App/Info.plist
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/bulletinBoardVector.imageset/Contents.json
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/bulletinBoardVector.imageset/bolletinBoardVector 1.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/bulletinBoardVector.imageset/bolletinBoardVector 2.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/bulletinBoardVector.imageset/bolletinBoardVector.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/profileIcon.imageset/Contents.json
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/profileIcon.imageset/profileIcon 1.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/profileIcon.imageset/profileIcon 2.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/profileIcon.imageset/profileIcon.svg
  dormitoryFamiles/dormitoryFamiles/Base/Base.lproj/Main.storyboard
  dormitoryFamiles/dormitoryFamiles/BulletinBoard/BrownVC.swift
  dormitoryFamiles/dormitoryFamiles/BulletinBoard/BulletinBoardMainViewController.swift
  dormitoryFamiles/dormitoryFamiles/BulletinBoard/BulluetinBoardCollectionViewCell.swift
  dormitoryFamiles/dormitoryFamiles/BulletinBoard/BulluetinBoardCollectionViewCell.xib
  dormitoryFamiles/dormitoryFamiles/BulletinBoard/RegisterPostViewController.swift
  dormitoryFamiles/dormitoryFamiles/Home/HomeViewController.swift
Labels: FEAT, DESIGN

#34 [FEAT] [#33] 게시물 찜하기
  dormitoryFamiles/dormitoryFamiles.xcodeproj/project.pbxproj
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/bulletinBoardDetailMore.imageset/Contents.json
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/bulletinBoardDetailMore.imageset/bulletinBoardDetailMore 1.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/bulletinBoardDetailMore.imageset/bulletinBoardDetailMore 2.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/bulletinBoardDetailMore.imageset/bulletinBoardDetailMore.svg
  dormitoryFamiles/dormitoryFamiles/Base/Base.lproj/Main.storyboard
  dormitoryFamiles/dormitoryFamiles/BulletinBoard/BrownVC.swift
  dormitoryFamiles/dormitoryFamiles/BulletinBoard/BulletinBoardDetailViewViewController.swift
  dormitoryFamiles/dormitoryFamiles/BulletinBoard/BulletinBoardMainViewController.swift
  dormitoryFamiles/dormitoryFamiles/BulletinBoard/BulluetinBoardCollectionViewCell.swift
  dormitoryFamiles/dormitoryFamiles/BulletinBoard/BulluetinBoardCollectionViewCell.xib
  dormitoryFamiles/dormitoryFamiles/BulletinBoard/Model/Category.swift
  dormitoryFamiles/dormitoryFamiles/BulletinBoard/Model/DateFomat.swift
  dormitoryFamiles/dormitoryFamiles/BulletinBoard/RegisterPostViewController.swift
  dormitoryFamiles/dormitoryFamiles/Network/Codable.swift
  dormitoryFamiles/dormitoryFamiles/Network/Network.swift
Labels: FEAT

#31 [#30, #31] FEAT: 게시물목록(페이징, 날짜세팅), 게시물 상세(프로필, 액션시트글메뉴, 댓글뷰 크기 동적 지정)
  dormitoryFamiles/dormitoryFamiles.xcodeproj/project.pbxproj
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/bulletinBoardDetailMore.imageset/Contents.json
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/bulletinBoardDetailMore.imageset/bulletinBoardDetailMore 1.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/bulletinBoardDetailMore.imageset/bulletinBoardDetailMore 2.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/bulletinBoardDetailMore.imageset/bulletinBoardDetailMore.svg
  dormitoryFamiles/dormitoryFamiles/Base/Base.lproj/Main.storyboard
  dormitoryFamiles/dormitoryFamiles/BulletinBoard/BrownVC.swift
  dormitoryFamiles/dormitoryFamiles/BulletinBoard/BulletinBoardDetailViewViewController.swift
  dormitoryFamiles/dormitoryFamiles/BulletinBoard/BulletinBoardMainViewController.swift
  dormitoryFamiles/dormitoryFamiles/BulletinBoard/BulluetinBoardCollectionViewCell.swift
  dormitoryFamiles/dormitoryFamiles/BulletinBoard/BulluetinBoardCollectionViewCell.xib
  dormitoryFamiles/dormitoryFamiles/BulletinBoard/Model/Category.swift
  dormitoryFamiles/dormitoryFamiles/BulletinBoard/Model/DateFomat.swift
  dormitoryFamiles/dormitoryFamiles/BulletinBoard/RegisterPostViewController.swift
  dormitoryFamiles/dormitoryFamiles/Network/Codable.swift
  dormitoryFamiles/dormitoryFamiles/Network/Network.swift
Labels: FEAT

#36 [#33] FEAT: 찜하기
  dormitoryFamiles/dormitoryFamiles/Base/Base.lproj/Main.storyboard
  dormitoryFamiles/dormitoryFamiles/BulletinBoard/BulletinBoardDetailViewViewController.swift
  dormitoryFamiles/dormitoryFamiles/BulletinBoard/SearchViewController.swift
  dormitoryFamiles/dormitoryFamiles/Network/Codable.swift
  dormitoryFamiles/dormitoryFamiles/Network/Network.swift
Labels: FEAT

#37 [DESIGN] 긱사생활 설정 / 생활습관 레이아웃
  dormitoryFamiles/Podfile.lock
  dormitoryFamiles/dormitoryFamiles.xcodeproj/project.pbxproj
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/Matching Option Setting/thumb.imageset/Contents.json
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/Matching Option Setting/thumb.imageset/Ellipse 70.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/Matching Option Setting/trackImage.imageset/Contents.json
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/Matching Option Setting/trackImage.imageset/Vector 18.svg
  dormitoryFamiles/dormitoryFamiles/BulletinBoard/BrownVC.swift
  dormitoryFamiles/dormitoryFamiles/BulletinBoard/BulletinBoardDetailViewViewController.swift
  dormitoryFamiles/dormitoryFamiles/Components/CustomSlider.swift
  dormitoryFamiles/dormitoryFamiles/Extension/UIImage+.swift
  dormitoryFamiles/dormitoryFamiles/Extension/UIScreen+.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/LifeStyleViewController.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/SleepPatternViewController.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/SmokeAndAlcoholPatternViewController.swift
  dormitoryFamiles/dormitoryFamiles/Network/Token.swift
  dormitoryFamiles/dormitoryFamiles/Network/Url.swift
Labels: iOS, FEAT, DESIGN
