Repository dormitoryFamilies/iOS, pull requests merged in 2024-08, with the labels that each got.

#79 [FEAT] 선택한 옵션 체크 로직 적용, 라벨 수정
  dormitoryFamiles/dormitoryFamiles/Components/ConfigUI.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/ChoosePriorityViewController.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/CompleteMyCondition.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/ConstitutionViewController.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/EatingFoodViewController.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/HomeCycleViewController.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/LifeStyleViewController.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/MBTIViewController.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/MiscViewController.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/NoiseAndPerfumeViewController.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/SleepPatternViewController.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/SmokeAndAlcoholPatternViewController.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/StudyStyleViewController.swift
Labels: iOS

#80 [FEAT] 웹소켓 통신
  dormitoryFamiles/Podfile
  dormitoryFamiles/Podfile.lock
  dormitoryFamiles/dormitoryFamiles.xcodeproj/project.pbxproj
  dormitoryFamiles/dormitoryFamiles.xcodeproj/xcuserdata/hwajin.xcuserdatad/xcschemes/xcschememanagement.plist
  dormitoryFamiles/dormitoryFamiles/App/Info.plist
  dormitoryFamiles/dormitoryFamiles/Base/Base.lproj/Main.storyboard
  dormitoryFamiles/dormitoryFamiles/Extension/Encodable+.swift
  dormitoryFamiles/dormitoryFamiles/Network/Codable.swift
  dormitoryFamiles/dormitoryFamiles/chat/ChattingDetailViewController.swift
  dormitoryFamiles/dormitoryFamiles/chat/ChattingHomeTableViewCell.swift
  dormitoryFamiles/dormitoryFamiles/chat/ChattingHomeViewController.swift
  dormitoryFamiles/dormitoryFamiles/chat/ChattingRoom/View/MyChattingTableViewCell.swift
  dormitoryFamiles/dormitoryFamiles/chat/ChattingRoom/View/YourChattingTableViewCell.swift
Labels: iOS, FEAT

#81 [FIX/FEAT] 스크롤 컨트롤 및 채팅방 나가기 구현
  dormitoryFamiles/dormitoryFamiles.xcodeproj/project.pbxproj
  dormitoryFamiles/dormitoryFamiles/App/AppDelegate.swift
  dormitoryFamiles/dormitoryFamiles/App/SceneDelegate.swift
  dormitoryFamiles/dormitoryFamiles/Network/Codable.swift
  dormitoryFamiles/dormitoryFamiles/Network/Network.swift
  dormitoryFamiles/dormitoryFamiles/chat/ChattingDetailViewController.swift
  dormitoryFamiles/dormitoryFamiles/chat/ChattingHomeTableViewCell.swift
  dormitoryFamiles/dormitoryFamiles/chat/ChattingHomeViewController.swift
  dormitoryFamiles/dormitoryFamiles/chat/ChattingRoom/View/YourChattingTableViewCell.swift
  dormitoryFamiles/dormitoryFamiles/chat/Model/WebSocketManager.swift
Labels: iOS, FEAT, FIX

#88 [FEAT] 우선순위 및 선호 룸메이트 설정 로직 구현
  dormitoryFamiles/dormitoryFamiles.xcodeproj/project.pbxproj
  dormitoryFamiles/dormitoryFamiles/Components/ConfigUI.swift
  dormitoryFamiles/dormitoryFamiles/Extension/UIScreen+.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/View/PriorityCell.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/ChoosePriorityViewController.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/ChooseRoomateViewController.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/CompleteMatchingOptionViewController.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/ConstitutionViewController.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/EatingFoodViewController.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/HomeCycleViewController.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/LifeStyleViewController.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/MBTIViewController.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/MiscViewController.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/NoiseAndPerfumeViewController.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/SleepPatternViewController.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/SmokeAndAlcoholPatternViewController.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/StudyStyleViewController.swift
Labels: iOS, FEAT

#92 [FIX] 룸메 매칭 설정 관련 수정사항 반영
  dormitoryFamiles/dormitoryFamiles.xcodeproj/project.pbxproj
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/Matching Option Setting/cancelButton.imageset/Contents.json
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/Matching Option Setting/cancelButton.imageset/Frame 1321318039.svg
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/Matching Option Setting/doomzList.imageset/Contents.json
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/Matching Option Setting/doomzList.imageset/Frame 1321319071.png
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/Matching Option Setting/recommendedMates.imageset/Contents.json
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/Matching Option Setting/recommendedMates.imageset/Frame 1321319072.png
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/Matching Option Setting/requestList.imageset/Contents.json
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/Matching Option Setting/requestList.imageset/Frame 1321319070.png
  dormitoryFamiles/dormitoryFamiles/Base/Base.lproj/Main.storyboard
  dormitoryFamiles/dormitoryFamiles/Components/CommomButton.swift
  dormitoryFamiles/dormitoryFamiles/Components/ConfigUI.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/View/SleepPatternCircleCollectionViewCell.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/View/SleepPatternCollectionViewCell.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/CompleteMyCondition.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/HomeCycleViewController.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/LifeStyleViewController.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/MBTIViewController.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/MatchingMainViewController.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/SleepPatternViewController.swift
  dormitoryFamiles/dormitoryFamiles/Matching Option Setting/ViewController/StudyStyleViewController.swift
Labels: iOS, FIX

#93 [FEAT] 온보딩 api연동 완료
  dormitoryFamiles/dormitoryFamiles.xcodeproj/project.pbxproj
  dormitoryFamiles/dormitoryFamiles.xcodeproj/xcshareddata/xcschemes/dormitoryFamiles.xcscheme
  dormitoryFamiles/dormitoryFamiles.xcodeproj/xcuserdata/hwajin.xcuserdatad/xcschemes/xcschememanagement.plist
  dormitoryFamiles/dormitoryFamiles/App/Info.plist
  dormitoryFamiles/dormitoryFamiles/Base/Base.lproj/Main.storyboard
  dormitoryFamiles/dormitoryFamiles/BulletinBoard/BulletinBoardDetailViewViewController.swift
  dormitoryFamiles/dormitoryFamiles/Network/Codable.swift
  dormitoryFamiles/dormitoryFamiles/Network/Network.swift
  dormitoryFamiles/dormitoryFamiles/Onboarding/LoginViewController.swift
  dormitoryFamiles/dormitoryFamiles/Onboarding/Model/UserInfomation.swift
  dormitoryFamiles/dormitoryFamiles/Onboarding/NickNameViewController.swift
  dormitoryFamiles/dormitoryFamiles/Onboarding/ProfileFinishedViewController.swift
  dormitoryFamiles/dormitoryFamiles/Onboarding/ProfileSettingViewController.swift
  dormitoryFamiles/dormitoryFamiles/Onboarding/StudentCertificationViewController.swift
Labels: iOS, FEAT

#94 [FEAT] 게시판-사진 완료
  dormitoryFamiles/dormitoryFamiles.xcworkspace/xcshareddata/swiftpm/Package.resolved
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/cancel.imageset/Contents.json
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/cancel.imageset/cancel.svg
  dormitoryFamiles/dormitoryFamiles/Base/Base.lproj/Main.storyboard
  dormitoryFamiles/dormitoryFamiles/BulletinBoard/AddImageBaseView.swift
  dormitoryFamiles/dormitoryFamiles/BulletinBoard/PhotoScrollView.swift
  dormitoryFamiles/dormitoryFamiles/BulletinBoard/RegisterPostViewController.swift
  dormitoryFamiles/dormitoryFamiles/Extension/UIButton+.swift
  dormitoryFamiles/dormitoryFamiles/Network/Codable.swift
  dormitoryFamiles/dormitoryFamiles/Network/Network.swift
  dormitoryFamiles/dormitoryFamiles/Onboarding/StudentCertificationViewController.swift
Labels: iOS, FEAT

#97 게시판 버그 잡기
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/like.imageset/Contents.json
  dormitoryFamiles/dormitoryFamiles/Base/Assets.xcassets/like.imageset/like.svg
  dormitoryFamiles/dormitoryFamiles/Base/Base.lproj/Main.storyboard
  dormitoryFamiles/dormitoryFamiles/BulletinBoard/BrownVC.swift
  dormitoryFamiles/dormitoryFamiles/BulletinBoard/BulletinBoardDetailViewViewController.swift
  dormitoryFamiles/dormitoryFamiles/BulletinBoard/BulletinBoardMainViewController.swift
  dormitoryFamiles/dormitoryFamiles/BulletinBoard/BulluetinBoardCollectionViewCell.swift
  dormitoryFamiles/dormitoryFamiles/BulletinBoard/Model/Category.swift
  dormitoryFamiles/dormitoryFamiles/BulletinBoard/RegisterPostViewController.swift
  dormitoryFamiles/dormitoryFamiles/BulletinBoard/ReplyHeaderCollectionReusableView.swift
  dormitoryFamiles/dormitoryFamiles/BulletinBoard/ReplyHeaderCollectionReusableView.xib
  dormitoryFamiles/dormitoryFamiles/BulletinBoard/SearchViewController.swift
  dormitoryFamiles/dormitoryFamiles/Home/HomeViewController.swift
  dormitoryFamiles/dormitoryFamiles/Home/MealOfWeekViewController.swift
  dormitoryFamiles/dormitoryFamiles/Network/Network.swift
  dormitoryFamiles/dormitoryFamiles/ReplyCollectionViewCell.xib
Labels: iOS, FIX

#99 [FEAT] 카카오 로그인/로그아웃/토큰관리
  dormitoryFamiles/Podfile
  dormitoryFamiles/Podfile.lock
  dormitoryFamiles/dormitoryFamiles.xcodeproj/project.pbxproj
  dormitoryFamiles/dormitoryFamiles/App/AppDelegate.swift
  dormitoryFamiles/dormitoryFamiles/App/Info.plist
  dormitoryFamiles/dormitoryFamiles/App/SceneDelegate.swift
  dormitoryFamiles/dormitoryFamiles/Base/Base.lproj/Main.storyboard
  dormitoryFamiles/dormitoryFamiles/BulletinBoard/BulletinBoardDetailViewViewController.swift
  dormitoryFamiles/dormitoryFamiles/BulletinBoard/RegisterPostViewController.swift
  dormitoryFamiles/dormitoryFamiles/Network/Network.swift
  dormitoryFamiles/dormitoryFamiles/Onboarding/LoginViewController.swift
  dormitoryFamiles/dormitoryFamiles/chat/ChattingHomeViewController.swift
  dormitoryFamiles/dormitoryFamiles/chat/Model/WebSocketManager.swift
  dormitoryFamiles/dormitoryFamiles/chat/SearchChat/AllViewController.swift
  dormitoryFamiles/dormitoryFamiles/chat/SearchChat/FollowingViewController.swift
Labels: iOS, FEAT
